on:
  push:
  pull_request:

jobs:
  re-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: resolve-gradle-deps
        run: nix develop -c resolve-gradle-deps
      - name: regen-lock
        run: nix develop -c regen-lock
      - name: ensure no changes
        run: git diff --exit-code && git diff --cached --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: build
        run: nix build -L
